# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing app source NPM dependencies...
      - cd bgacb-client && npm install
  build:
    commands:
      - npm run build:prod --verbose
# Include only the files required for your application to run.
artifacts:
  files:
    - "**/*"
  base-directory: bgacb-client/dist
