# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing api source NPM dependencies...
      - npm install -g typescript
      - npm install
  build:
    commands:
      - npm run build
# Include only the files required for your application to run.
artifacts:
  files:
    - package.json
    - package-lock.json,
    - "dist/**/*"
  discard-paths: no
